### ISSUE TITLE
Hydxlib tasks

### ISSUE THREAD

**Issue by caspervdw** [nens/hydxlib#21]
- [x] Migrate the changes in github.com/threedi/beta-plugins/tree/master/import_hydx/hydxlib to https://github.com/nens/hydxlib
- [x] Rebase hydxlib on threedi-modelchecker and add it as dependency (newest 3Di schema version)
- [x] Clean up unused files in hydxlib
- [x] Include automated tests in hydxlib (using example file (https://github.com/nens/ThreeDiToolbox/files/9764353/HydX.example.data.zip) and a spatialite with the newest 3Di schema version)
- [x] Publish a new version of hydxlib on PyPI

**Comment by caspervdw** [comment]
Ref. https://github.com/nens/ThreeDiToolbox/issues/470

**Comment by caspervdw** [comment]
Some questions while rebasing on threedi-modelchecker @leendertvanwolfswinkel :

- `manhole.shape` has an enumerator here (`sqr`, `rect`, `rnd`), 3Di schema doesn't have that and accepts any string with length <= 4
- `pipe.material` appears to has an enumerator here (0 = beton, 1 = pvc, etc. t/m 8), 3Di schema doesn't have that and accepts any integer
- `manhole.manhole_indicator` has an enumerator here (0 = manhole, 1 = outlet, 2 = pump), 3Di schema doesn't have that and accepts any integer
- in de shape mapping: moeten we "RHK" niet als "closed rectangle" interpeteren ipv "rectangle"?

**Comment by leendertvanwolfswinkel** [comment]
My reactions:
1. Could be a nice addition, WARNING or INFO level. For visualization purposes in the future it could be nice to do this. BTW wouldn't it be more consistent to make this an integer value, like the other enums in the database schema?
2. Same as 1.
3. Same as 1.
4. Zeker!

**Comment by caspervdw** [comment]
@leendertvanwolfswinkel   I did not port the enumerators of manhole.shape, pipe.material, manhole.manhole_indicator. It is possible to do that in the future, but first @nvolp  and I wanted a broader discussion of what to do with fields that are in the sqlite but not used by 3Di.

Apart from that, my work on hydxlib seems to be done. Version 1.0 is now on PyPI: https://pypi.org/project/hydxlib/1.0/
