### ISSUE TITLE
Add Ovaal (OVA) profile

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/hydxlib#31]
Definition: https://data.gwsw.nl/1.5.2/Basis/index.html?menu_item=individuals&item=../../def/1.5.2/Basis/Ovaal

**Comment by leendertvanwolfswinkel** [comment]
I looked into this a bit more, and it turns out we can simply interpret this in the same way as tabulated trapezium. The only thing is that we may need to remove the first (height, width) pair if it is (0, 0)

**Comment by caspervdw** [comment]
I think it is more useful to implement this in the `threedigrid-builder` and add it as a new crossection definition type.

**Comment by leendertvanwolfswinkel** [comment]
OK. This profile also does not occur in the Rotterdam dataset, so not critical for the current project

**Comment by caspervdw** [comment]
Issue moved to [nens/threedigrid-builder #271](https://github.com/nens/threedigrid-builder/issues/271) via [**Zenhub**](https://www.zenhub.com/)
