### ISSUE TITLE
Add YZ profile (YZP)

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/hydxlib#32]
Definition: Conform de gangbare aanduiding voor open water: een curve die de dwarsdoorsnede beschrijft over YZ, waarden in [m].

**Comment by leendertvanwolfswinkel** [comment]
This YZ profile converter by @Ckerklaan and @Overmeen could be useful:

https://github.com/nens/threedi-model-edits/blob/main/threedi_model_edits/cross_section_definitions/profile_tool.py

**Comment by caspervdw** [comment]
I think it is more useful to implement this in the `threedigrid-builder` and add it as a new crossection definition type.

**Comment by leendertvanwolfswinkel** [comment]
Agree. Would be an appreciated feature with much wider use than HydX. Actually, I think it is quite unlikely to encounter a YZ profile in sewerage data, whereas this is pretty common in open channel flow profiles.

This is not critical path stuff for our current GWSW HydX project.

**Comment by caspervdw** [comment]
Issue moved to [nens/threedi-tables #205](https://github.com/nens/threedi-tables/issues/205) via [**Zenhub**](https://www.zenhub.com/)
