### ISSUE TITLE
Implement "YZ" (YZP) and "Eivormig omgekeerd" (EIG) profiles

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/hydxlib#40]
Depends on implementation of extra profiles in other threedi repo's:
- https://github.com/nens/threedigrid-builder/issues/270
- https://github.com/nens/threedi-tables/issues/205 (@caspervdw shouldn't this be in threedigrid-builder instead of threedi-tables?)

**Comment by caspervdw** [comment]
versie 1.3 is nu op PyPI en bevat alle profielen, dit ticket is dus klaar
